export enum EnumScopes {
  USER = `DEVSEEDER/HANGMAN/API/USER`,
  ADM = `DEVSEEDER/HANGMAN/API/ADM`,
  GET_ALL = `DEVSEEDER/HANGMAN/API/GET_ALL`,
  UPDATE_PASSWORD = `DEVSEEDER/HANGMAN/API/UPDATE_PASSWORD`
}

export const SCOPE_KEY = 'DEVSEEDER/HANGMAN/API';
